name: Install and test
# This will not trigger any release to pypi.org
on: [push]

jobs:
  install-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7']
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: install-and-test
        working-directory: ./
        run: |
          pip install .
          pip install -r dev-requirements.txt
          py.test tests/
